### ISSUE TITLE
Add multiple languages 

### ISSUE THREAD

**Issue by fonsleenaars** [fonsleenaars/tqdb#10]
The resources contain multiple languages, adding these should be possible.

Some of the properties are currently hard-coded, these should be updated to rely on language resources instead.

**Comment by LordVampir1983** [comment]
Is it planned to add it to the site as well or is it just for the parser?

**Comment by fonsleenaars** [comment]
Both!

**Comment by LordVampir1983** [comment]
Very very gooD  :+1:

**Comment by fonsleenaars** [comment]
An initial preview of the multiple locales is available on https://staging.tq-db.net/

This is still an early stage and will be updated frequently this next week before it goes live. Translation files will be made available at some point for those wanting to help with translations.

**Comment by fonsleenaars** [comment]
Version 1.0 has been deployed to tq-db.net.
