### ISSUE TITLE
Oracle's Leggings - Req Level is 9 not 10

### ISSUE THREAD

**Issue by crashinz** [fonsleenaars/tqdb#103]
https://tq-db.net/en/search/oracle's+leggings

it says lvl 10 but mine require lvl 9 to equip.

**Comment by fonsleenaars** [comment]
👍🏻 Thanks for reporting, I always thought my level logic wasn't complete yet, will need to see what else factors into it, or if this was maybe a rounding error or something.

**Comment by fonsleenaars** [comment]
![image](https://user-images.githubusercontent.com/4301261/171048423-cf6a0a5a-e18a-46b6-aa92-628d32105d80.png)
Keeping this as a reference

**Comment by fonsleenaars** [comment]
Moving larger discussion to #113 - adding this to 1.4.4 milestone
