### ISSUE TITLE
New expansion: Eternal Embers

### ISSUE THREAD

**Issue by TheWagi** [fonsleenaars/tqdb#104]
Hey o/

There is a new expansion, making sure you're aware.
Will you be able to update TQ DB ?

Wagi

**Comment by fonsleenaars** [comment]
👍🏻 thanks, I've got some time scheduled over my Christmas break so I'll add this to the list

**Comment by fonsleenaars** [comment]
Doing some house keeping, closing this since I shipped the initial version of this with the 1.3.10 update on Jan 9th. 
I have plenty of cleanup to do it seems though 😅 

Thanks for creating the ticket & letting me know @TheWagi
