### ISSUE TITLE
Error due parsing

### ISSUE THREAD

**Issue by echefranov** [fonsleenaars/tqdb#105]
Hi! I tried run parse and faced with errors

![image](https://user-images.githubusercontent.com/40499300/145473102-e2f503a8-7102-4d75-b27f-dc9390acbfd8.png)

Then I tried install these modules manually: `pip install numexpr Pillow pytest` and it installed

![image](https://user-images.githubusercontent.com/40499300/145473247-9d0b1132-eb52-4156-b7b6-ed7572fdacd0.png)

After then I run parse and got error

![image](https://user-images.githubusercontent.com/40499300/145473339-502a535d-5710-4f72-8706-3568985272e2.png)

OS: Windows 11

@fonsleenaars could you help me?

**Comment by echefranov** [comment]
I found this solution 
```import sys
sys.path.append("C://Users//echef//AppData//Local//Programs//Python//Python310//Lib//site-packages")```
but now I ave new issue:

![image](https://user-images.githubusercontent.com/40499300/145526607-00f85db4-67af-4077-833f-9932d4d5e9e7.png)

**Comment by fonsleenaars** [comment]
I'm working on some fixes for the new expansion pack, I'll be pushing commits in the next few weeks for them.

However the old TextureViewer utility no longer works on the latest DLC so I'm stuck trying to figure that out. I'll keep you posted.

**Comment by prouhard** [comment]
@fonsleenaars Do you need help with the textures ? I may have some time to rewrite a parser with Python

**Comment by fonsleenaars** [comment]
@prouhard I appreciate the offer, one of the people from the Titan Quest mod community reached out and got me a solution, so I'm giving that a whirl this weekend!

**Comment by chefranov** [comment]
@fonsleenaars hi! Any updates? Holidays are finished 😊

**Comment by fonsleenaars** [comment]
@chefranov just pushed the commit to master that allowed me to parse Eternal Ember, currently deploying it to tq-db's website

**Comment by chefranov** [comment]
Now it works! Thank you! You can close the ticket.
