### ISSUE TITLE
Missed loot tables for Eternal Embers

### ISSUE THREAD

**Issue by chefranov** [fonsleenaars/tqdb#106]
Hi! I have noticed empty loot tables for Eternal Embers. Could you double check it?

![image](https://user-images.githubusercontent.com/2775475/148747824-470d231d-f7f5-4821-99c8-cf433be8c0db.png)

![image](https://user-images.githubusercontent.com/2775475/148747893-05c61780-cb1f-4a8e-a1fd-569f02af1b58.png)

**Comment by fonsleenaars** [comment]
I expect this is because I haven't parsed the new bosses yet properly, I need to find all of their unique IDs.

**Comment by chefranov** [comment]
When can we expect a fix?

**Comment by fonsleenaars** [comment]
I can't actually find a single reference to some of these items in loot tables or anything else. It's possible this is an unreleased set of items.
