### ISSUE TITLE
Field "name" in new DLC

### ISSUE THREAD

**Issue by chefranov** [fonsleenaars/tqdb#108]
After latest game updated (2.10.19714) in genereted json file I have noticed that "name" field contains `x4tagU_*` instead of name of my language. Can you fix it? Also need to update the site because in latest patches many changes in loot tables.

```
{
        "classification": "Легенда",
        "dexterityRequirement": 200,
        "itemLevel": 70,
        "levelRequirement": 70,
        "name": "x4tagU_Axe05",
        "properties": {
          "characterAttackSpeed": "Скорость: Средняя",
          "characterIncreasedExperience": "-17% увеличения опыта",
          "offensiveLifeLeech": "5% урона переводится в жизнь",
          "offensivePhysical": "202-214 ед. физического урона"
        },
        "set": "x4tagU_Set_10",
        "strengthRequirement": 400,
        "tag": "x4tagU_Axe05"
      }
```

Also some items don't have "name" 

![image](https://user-images.githubusercontent.com/2775475/149793348-eca1a997-9e66-47df-9d5b-a1b3578ab950.png)

**Comment by fonsleenaars** [comment]
Deployed
