### ISSUE TITLE
Missing Set - Ritualist / Wrong values in EE items.

### ISSUE THREAD

**Issue by M2etroline** [fonsleenaars/tqdb#109]
Missing Set: Ritualist
![image](https://user-images.githubusercontent.com/67417954/164551934-5474aa25-8027-48bd-99f9-db9be515d884.png)

Gan Jiang's Razor
+15% not +35% dex
![image](https://user-images.githubusercontent.com/67417954/164551497-233f06c3-0eb7-4a68-9e87-40334546e97d.png)

Entropy
150-200 not 350-415 elemental damage
![image](https://user-images.githubusercontent.com/67417954/164552283-6fe14b60-b8af-446d-8148-f3ec71596ad8.png)

Wang Shan's Curiass of Liberation
+60 not +150 strength
![image](https://user-images.githubusercontent.com/67417954/164552667-50122f4c-7bb8-44aa-81be-09a812efa221.png)

These are the ones i noticed, since after farming for the items they turned out to be worse than advertised :')
Its strange, i thought the data comes from the database.arz file.

**Comment by fonsleenaars** [comment]
Cool, thanks for letting me know, I'll debug these and see what's going wrong with my parser.

THey do indeed come from `database.arz`

**Comment by fonsleenaars** [comment]
Looks like both of the items are there, but the sets aren't being parsed, so this should be a relatively easy fix.

**Comment by fonsleenaars** [comment]
All of them have been solved since their bug fixes, I'll publish a new data set soon and will close this when I have.

**Comment by fonsleenaars** [comment]
Deployed, should be good now
