### ISSUE TITLE
Incorrect sprite

### ISSUE THREAD

**Issue by chefranov** [fonsleenaars/tqdb#111]
I ran a new realease and I got incorrect sprite.png or sprite.css. I think incorrect coordinates

![image](https://user-images.githubusercontent.com/2775475/170115159-084b5eb0-9bb5-4e9d-a3f6-5c9e8908de64.png)

**Comment by fonsleenaars** [comment]
👍🏻 Running it myself at the moment and will debug, I have 2 days off so hopefully I can cross some things off.

**Comment by fonsleenaars** [comment]
@chefranov mine looks mostly ok, what item is your screenshot?

**Comment by chefranov** [comment]
https://tq-db.net/en/equipment/strength-of-the-nile

**Comment by fonsleenaars** [comment]
![image](https://user-images.githubusercontent.com/4301261/170116987-742e7733-20e4-4fd5-a2e3-1fb2359d415c.png)

Hm, mine looks ok. I'm fixing a few more things and going to try and publish something on Thursday or earlier, if you want you can grab the source files I put up at that point.

**Comment by fonsleenaars** [comment]
Deployed if you want to use that sprite sheet

**Comment by chefranov** [comment]
Still have this issue

![image](https://user-images.githubusercontent.com/2775475/170227337-98d05399-dd74-427f-9365-fca2ff45b10d.png)

What I got after parsing

https://chefranov.name/wp-content/uploads/2022/05/output.zip

Can you check? Maybe it connected with Windows OS or locale parameter

**Comment by chefranov** [comment]
I also took your sprite (png) from your site. The same. Your sprite (css) I didn't take because it's different, encoded classes

**Comment by chefranov** [comment]
I figured out. It was cache for me

**Comment by fonsleenaars** [comment]
Nice - glad you got it solved.
