### ISSUE TITLE
Throwin weapons targeting

### ISSUE THREAD

**Issue by Dajuicy** [fonsleenaars/tqdb#13]
When using throwing weapons, you have to walk up to your enemy more than your character initially does when you target an enemy. Making it pretty frustrating when targeting enemies that are out of reach of your weapon.

**Comment by fonsleenaars** [comment]
@Dajuicy This isn't a repository from the actual game developers, I just maintain a database of the items & equipment from that game called Titan Quest Database (found at tq-db.net).

Or was there an issue with the database in regards to throwing weapons? If so, let me know!

**Comment by Dajuicy** [comment]
Wow sorry Fons you're right, my bad...

2017-12-28 22:07 GMT+01:00 Fons Leenaars <notifications@github.com>:
