### ISSUE TITLE
Running list of TQ item issues

### ISSUE THREAD

**Issue by fonsleenaars** [fonsleenaars/tqdb#17]
Some of the issues are unfixable by the parser because the data of the actual files is incorrect. These can be communicated to the development team, but having them organized in one place is pretty useful. Since I run in to them while working on the parser, I figured I'd compile them here, that way anybody else that's on the tq-db.net website that notices something can add them, and if after digging a bit I realize it's an issue with the records and not the parser, I can add them here.

- [x] Missing Greater Scroll of Svefnthorn
- [x] Add missing Ragnarok property
https://github.com/fonsleenaars/tqdb/issues/17#issuecomment-354695693
- [x] Fix names
https://github.com/fonsleenaars/tqdb/issues/17#issuecomment-354659022

**Scroll of Svefnthorn**
The Greater Scroll of Svefnthorn is missing because it has the same tag as Divine Scroll of Svefnthorn.
dir: `records\xpack2\item\scrolls`
file: `02_svefnthorn.dbr`
property: `description,x2tagScrollName11`
Should be: `description,x2tagScrollName06`

**Comment by Giant2005** [comment]
Items are missing the new bonuses from their stats (bonuses that did not previously exist such as the conversion of damage to elemental).
Take a look at your [Pearled Cap](https://www.tq-db.net/equipment/pearled-cap) for instance and compare it to the [real thing](https://i.imgur.com/x1nMU1k.jpg?1), It has everything except the one bonus that makes it unique. I think there are many new items with that bonus, but that bonus isn't listed at all on the site.

**Comment by fonsleenaars** [comment]
Fantastic, that's really useful! If you have more screenshots of new items, keep them coming.

I'll run through the new properties and add them with the next push.

**Comment by Giant2005** [comment]
I really don't want to have to go through the task of uploading so many pictures, but if you want, I can just tell you the ones I notice.
I am busy compiling all of the Ragnarok stuff in to a single vault. I can send you the vault when I am finished so you can verify.

The Falcon Cape has a 50% version of that same unlisted ability.

**Comment by Giant2005** [comment]
Here it is. This [Vault](https://www.dropbox.com/s/pq4hu3z3ov3wheq/Ragnarok.vault?dl=0) should have all of the Epic and Legendary Ragnarok items in it.

**Comment by fonsleenaars** [comment]
Yeah that makes sense, Vault works fine. So far I've only been able to find one new property (the elemental conversion) in the DLC.

Name are tricky, I extract lists from the database and Titan Quest uses tags to reference names. I'll have to see where the incorrect names are coming from.

I imagine the broken links are UTF-8 related, the * item (staff, first one in the list) also can't be hotlinked because it filters out the * as a non-valid character. I'll make a separate issue for that based on your comment.

Thanks!

**Comment by fonsleenaars** [comment]
I believe all of these have been fixed and verified on staging (eg. https://staging.tq-db.net/equipment/greater-scroll-of-the-svefnthorn).
