### ISSUE TITLE
About the chance of ONE item

### ISSUE THREAD

**Issue by gx16377** [fonsleenaars/tqdb#21]
"For chest loot, the chance listed is the chance of any ONE item that falls out"
How about multiply that by (numSpawnMaxEquation + numSpawnMinEquation)/2 ?
(In FixedItemLoot dbrs and let numberOfPlayers=1)

**Comment by fonsleenaars** [comment]
Average it out huh? Not a bad idea, I had something else in mind when I decided against using the equation (adding config on the website to set your character(s) level and have the loot table respond to whatever your input), but your solution will be quicker to implement and work well enough for now.

**Comment by gx16377** [comment]
At least I can compare it to the equiped chance in this way :)
