### ISSUE TITLE
Update scripts

### ISSUE THREAD

**Issue by LordVampir1983** [fonsleenaars/tqdb#3]
Hi.

Please, update pyton-scripts for `Titan Quest Ragnarok`

Theanks

**Comment by fonsleenaars** [comment]
Working on it! Bit busy this weekend but should have the next parser ready next week.

**Comment by LordVampir1983** [comment]
Very good :+1:

**Comment by fonsleenaars** [comment]
I've started work on it, initial parse got about 80% of the way through before I ran into some issues. Will update code here when it's ready. Should be this week.

**Comment by LordVampir1983** [comment]
O'Key, no problem :100:

**Comment by fonsleenaars** [comment]
Alrighty, I've been able to parse through 100% of the new database, just need to fix some edge cases (missing equipment from 1 set) and add the boss loot.

Should be done this weekend.
