### ISSUE TITLE
Add editing for hero?

### ISSUE THREAD

**Issue by ghost** [fonsleenaars/tqdb#31]
I see theres a lot of threads on internet/steam discussions about editing hero (mastery, skill points etc.), we need to use some programmes like TQVault/TQDefiler, but with Ragnarok it's not working correctly. Can u add something like this, or add a character on Helos on each difficulty levels who will do it for like 5 millions (or other large amount of money :D). It will be useful for all who like to combine with their hero.

**Comment by fonsleenaars** [comment]
Do you mean a combination titancalc (updated for Ragnarok here https://www.kirmiziperfect.com/titancalc-anniversary-edition/) and then on top of that, adding equipment to your character?

That won't be a part of tq-db in the forseeable future. I'm currently focusing on getting the equipment database (all properties, loot tables, etc) up to a 100% accuracy relative to the game.

Or do you mean something else? :)
