### ISSUE TITLE
Dvalinn's Simulacrum

### ISSUE THREAD

**Issue by ProfessorBelle** [fonsleenaars/tqdb#32]
The greater artifact "Dvalinn's Simulacrum" is missing information. It does not seem to offer any information on what it actually gives. Ie, the only things in the "properties" tab are "From Arcane Formula - Dvalinn's Simulacrum" and "Grants skill: Dvalinn's Simulacrum (show details)" with the skill not having any details either.

Checklist (note: MI's [ie. Kelpie Circlet through to Bear Rider's Braces] include all difficulties):

- [x] Dvalinn's Simulacrum

- [x] The Fleeting Memory

- [x] Rhodian Sling

- [x] Electrum Sling

- [x] Teutoburg Tunic

- [x] Britomaris' Defiance

- [x] Fine Gallic Boots

- [x] Kelpie Circlet

- [x] Kelpie Vambrace

- [ ] Bear Rider's Garb

- [ ] Bear Rider's Leggings

- [ ] Bear Rider's Bracers

- [x] Scroll of the Storm Witches

- [x] Scroll of the Sky's Rage

- [x] Scroll of the Breaking Wheel

- [x] Greater Scroll of the Storm Witches

- [x] Greater Scroll of the Djinn

- [x] Greater Scroll of the Necromancer

- [x] Greater Scroll of the Breaking Wheel

- [x] Divine Scroll of the Maddened God

- [x] Divine Scroll of the Breaking Wheel

- [x] Divine Scroll of the Behemoth

**Comment by fonsleenaars** [comment]
Thanks for making the issue, I'll look into it. Been busy & sick last week so haven't gotten around to the latest updates yet.

**Comment by ProfessorBelle** [comment]
While I'm at it, similar issue on "The Fleeting Memory", the helmet from the "The Shade" set, which also seems to be missing it's set item bonuses (assuming it has them). I might go through when I have the time and compile a list of any other items I find with a similar issue.

**Comment by ProfessorBelle** [comment]
Here is my list (always going under the assumption that items that are MI's or higher are very likely to have something in the properties tab)

Other Epic/legendary items with a similar issue: Rhodian Sling, Electrum Sling, Teutoburg Tunic.

Epic/Legendary Items which have suspicious properties (both these only display movement speed and I find it unlikely that that is the only property they have): Britomaris' Defiance, Fine Gallic Boots.

MI's which have a similar issue: Kelpie Circlet, Bear Rider's Bracers, Kelpie Vambrace, Bear Rider's Garb, Bear Rider's Leggings

Scrolls which have a similar issue: Scroll of the Storm Witches, Scroll of the Sky's Rage, Scroll of the Breaking Wheel, Greater Scroll of the Storm Witches, Greater Scroll of the Djinn, Greater Scroll of the Necromancer, Greater Scroll of the Breaking Wheel, Divine Scroll of the Maddened God, Divine Scroll of the Breaking Wheel, Divine Scroll of the Behemoth.

If I happen upon anything else I will let you know. Also thank you for the resource, I, and I'm sure many other people are very grateful to have it, and thank you for your swift response.

**Comment by fonsleenaars** [comment]
You're welcome, and thank you for the list! Wish I had more time last few weeks, I miss fixing up the parser & db!

What you can do is copy your list from the comment and edit your original issue and then use the checklist button to make each item a checklist, that way I can check them off when I fix them to make sure I've got them all.

- [ ] Checklist example 1
- [x]  Checklist example that's checked!

**Comment by ProfessorBelle** [comment]
Done and thank you!

**Comment by fonsleenaars** [comment]
I'm starting work on this today, some are already fixed by the latest version of the parser so I'll begin checking those off.

The ones that are missing are mostly because summons aren't parsed correctly yet, Dvalinn's Simulacrum seems to be summon related.

Then there are a few I'll have to dive into deeper because TQVault doesn't seem to have the correct rendering (or the items are broken) either. Either way, work is finally being done ;)

**Comment by fonsleenaars** [comment]
Most of the fixes (I'm fixing Dvalinn as we speak) are live on staging (eg. https://staging.tq-db.net/equipment/scroll-of-the-breaking-wheel)

**Comment by fonsleenaars** [comment]
Dvalinn's is now fixed (https://staging.tq-db.net/equipment/dvalinns-simulacrum)

**Comment by fonsleenaars** [comment]
The Rhodian and Electrum Sling's don't drop as it turns out, their files have no properties in them, and in the description it says

`X-Does not drop-X`

I'll add a filter to remove them from parsing.

**Comment by fonsleenaars** [comment]
The Bear Rider's items just don't have any values in their files, it's all `0.00000` except the armor. I'll have to farm it in-game or get a drop from it somewhere to see what the game says it should be. Closing this until I have more information!
