### ISSUE TITLE
Blacksteel Spike incorrect

### ISSUE THREAD

**Issue by DicksonWU** [fonsleenaars/tqdb#33]
I find a different in database with game of Blacksteel Spike
I thought this Blacksteel Spike drop in last map just only 282 Physical Damage is not very reasonable.
Not conforming to the definition of this equipment

(295 ~ 313 Physical Damage,45% Pierce Ratio) in database
(266~282 Physical Damage, 40% Pierce Ratio) in game.

**Comment by fonsleenaars** [comment]
Thanks for the issue report, I think it'll automatically be fixed when some other issues are fixed but I'll check it afterwards, just going to update your title & description a bit :)

**Comment by fonsleenaars** [comment]
Fixed locally, close when milestone is completed.

**Comment by fonsleenaars** [comment]
Fixed, verified on staging (https://staging.tq-db.net/equipment/blacksteel-spike-legendary)
