### ISSUE TITLE
Add sorting by monsters/bosses please.

### ISSUE THREAD

**Issue by MadYarl** [fonsleenaars/tqdb#37]
Sorry for bad english. I translated with google. 

You can add sorting by monsters from which items fall.
There will be a section on the side - "monsters". There are three tabs "normal", "epic", "legendary".
Click on the tab. 
There appears a list of monsters. 
Example for "normal".
(ACT I)
.
.
. Nehebkau ~ Scorpos King
.
.

(ACT II)
.
.
.

....................
-------------------------
After that
Click on some monster. 
A list of items(as in "weapons" -> "axe" or another tabs) that can be dropped from the monster appears. 
Example for "normal" --> Nehebkau ~ Scorpos King.
"Obsidian Crescent"  |   "Mikros"   |   "Raging Bull".........
.........
........
........

**Comment by fonsleenaars** [comment]
Monsters page has been implemented.
