### ISSUE TITLE
The Trackmaster Set

### ISSUE THREAD

**Issue by sircrimer** [fonsleenaars/tqdb#38]
The item set only displays 1 of the 4 items.

**Comment by fonsleenaars** [comment]
Thanks for reporting

**Comment by fonsleenaars** [comment]
Fixed in upcoming 1.2.0 release, will check and close after it's deployed.

**Comment by fonsleenaars** [comment]
Fixed, verified on staging (https://staging.tq-db.net/set/the-trackmaster).
