### ISSUE TITLE
Affixes doesn't say which sort of items they are eligible for

### ISSUE THREAD

**Issue by DiomedesofHelos** [fonsleenaars/tqdb#39]
Hi.
I really love the site, but if I want a green legs armor for an example, it is hard to know which prefixes and suffixes that there's even a chance of them having. Therefore not possible for me to plan, if the prefix I want can only occur on a ring or another item that isn't legs armor.
Is it possible to update the affixes to say which kinds of green and yellow items they can occur on? Does anyone even know?
Ps. Otherwise the site is perfect, except I don't quite understand why the Adamantine Sickle of Kronos isn't there along with all the basic non-magical pieces of armor and weapons which are the ones that can have all the affixes.

**Comment by fonsleenaars** [comment]
Definitely possible, it's already reported in #6 ;) Feel free to close it yourself if #6 accurately describes what you're asking for!

**Comment by DiomedesofHelos** [comment]
Thank you very much, cheers!

**Comment by DiomedesofHelos** [comment]
Do you have any idea at all of when the page will be updated to show it?:-)

2018-05-22 10:27 GMT+02:00 Asgerr Storgaard-Larsen <seth.storgaard@gmail.com
>:

> Thank you very much, cheers!
>

**Comment by fonsleenaars** [comment]
Hm, hard to give an estimate at the moment, I'm trying to make time for TQDB so I'll see if I can update the release schedule to something more concrete. Maybe 3-4 weeks?

**Comment by DiomedesofHelos** [comment]
Sounds amazing!!!!xD
Thank you, it really is the best tq site I've ever seen!!;-)

**Comment by DiomedesofHelos** [comment]
Hello! Do you know more about which date the affixes will tell which kind
of item they may belong to? :)
Also I found a blue item called Bormo's Arm Ring, but it's not in the
database. How can that be?
Keep up the good work, I really appreciate it

2018-05-22 15:58 GMT+02:00 Asgerr Storgaard-Larsen <seth.storgaard@gmail.com
>:

> Sounds amazing!!!!xD
> Thank you, it really is the best tq site I've ever seen!!;-)
>

**Comment by fonsleenaars** [comment]
Thanks, I'll check if Bormo's Arm Ring is in the latest release I've been working on locally.

I think for the affix information, probably mid july by the latest? I've got 2 weeks holiday at the end of June that I plan to use to get a lot of issues worked through for this project, so the release following that holiday will probably have the affix fix in it! Wish I had more time to spend on this project, it's a lot of fun!

**Comment by DiomedesofHelos** [comment]
Sounds great! Im so glad you think its fun! It helps a lot of us!! :)

**Comment by DiomedesofHelos** [comment]
Is it going well with patching the site? ;)

2018-06-05 20:10 GMT+02:00 Asgerr Storgaard-Larsen <seth.storgaard@gmail.com
>:

> Sounds great! Im so glad you think its fun! It helps a lot of us!! :)
>

**Comment by fonsleenaars** [comment]
Somewhat slowly since work is busy at the moment, after this week I have another week holiday so I expect that to be the week I can finally wrap it up. Sorry for the delay!

**Comment by DiomedesofHelos** [comment]
It's okay, I just appreciate your work. Thank you for keeping it up!:)

**Comment by fonsleenaars** [comment]
Parser changes have been completed, I'm updating the website so it can handle the new information.

Maybe 1 more week until it's done.

**Comment by DiomedesofHelos** [comment]
Awesome, great news! Thank you :)

**Comment by DiomedesofHelos** [comment]
It's gonna be so great :D

**Comment by fonsleenaars** [comment]
Oh I was looking for this issue, here's the update on staging: https://staging.tq-db.net/affix/prefixes

Once I fix a few more bugs it will go on the main website.

**Comment by DiomedesofHelos** [comment]
Can't thank you enough for that, you're so cool!

**Comment by DiomedesofHelos** [comment]
Btw I just noticed "Of the Mammoth" is in prefixes instead of suffixes, is
it supposed to be there? And it says it's only for reference. Just if you
were looking for bugs :P

2018-08-14 22:05 GMT+02:00 Asgerr Storgaard-Larsen <seth.storgaard@gmail.com
>:

> Can't thank you enough for that, you're so cool!
>

**Comment by DiomedesofHelos** [comment]
And also, do you know where then to find the items with the affixes that
says they are only for reference, if they aren't found on common items?

2018-08-14 23:29 GMT+02:00 Asgerr Storgaard-Larsen <seth.storgaard@gmail.com

**Comment by DiomedesofHelos** [comment]
And lastly, aren't the requirements listed for all the Ragnarok items?

2018-08-14 23:30 GMT+02:00 Asgerr Storgaard-Larsen <seth.storgaard@gmail.com

**Comment by fonsleenaars** [comment]
> Of the Mammoth

Good catch thanks

> only for reference

This basically means they cannot occur in-game, only if somebody were to write a mod that uses it, could they be found

> requirements listed for all the Ragnarok items

I'll take a look, thanks for reporting!

**Comment by DiomedesofHelos** [comment]
Thank you so much too!:)

**Comment by DiomedesofHelos** [comment]
It might not only be the Ragnarok items, a lot of items, especially the
monster infrequents, seems to be missing the stat requirements. Also some
of them seems to be messed up, where the epic version of the item requires
more strength fx, than the legendary version of that same item... Mysterious

2018-08-15 12:36 GMT+02:00 Asgerr Storgaard-Larsen <seth.storgaard@gmail.com
>:

> Thank you so much too!:)
>

**Comment by DiomedesofHelos** [comment]
Sorry to constantly notify you, but I noticed that the -15.00 health
regeneration for the prefix "Defiled" doesn't show in the updated version
of the site as of now.

**Comment by fonsleenaars** [comment]
No problem at all, I appreciate the bugreports, I'm just going to reopen this issue so I don't forget!

I'll respond later to the bugs, at work atm!

**Comment by DiomedesofHelos** [comment]
Yes sir!

**Comment by DiomedesofHelos** [comment]
Also sets display bonuses for having their items improperly, as if there
are a bonus for having more items in the set than there even are of items
in it.
These are all not the biggest issues, to me, the biggest issue is just that
all items don't display the stat requirements needed for them. Except for
the level maybe, but not the stats that you need.

**Comment by fonsleenaars** [comment]
- [x] Of the Mammoth (this is tagged as a Prefix internally, I'll add an exception note at some point)
- [ ] Defiled is lacking -15.00 HP regen
- [ ] Requirements missing
- [ ] Set display bonuses incorrectly

**Comment by DiomedesofHelos** [comment]
Very cool (Y) :)

**Comment by fonsleenaars** [comment]
The requirements (for the MIs at least) seem to just not be set, even compared to the current tq-db.net.

I checked the files and they're not in there either. I think it might be largely in part of the MIs having affix requirements, instead of base ones. It's strange because in many instances it looks like the [Normal](https://staging.tq-db.net/equipment/deathweavers-helmet-normal) version has a requirement but the [Epic](https://staging.tq-db.net/equipment/deathweavers-helmet-epic) and [Legendary](https://staging.tq-db.net/equipment/deathweavers-helmet-legendary) versions don't.

Did you find any epic/legendary item without requirements? If so, link me that.

**Comment by fonsleenaars** [comment]
Thanks!

Yeah that's true, I kind of need a screenshot from the current in-game for one of those examples of MIs without requirements. I think I have a high level character I can use to go do some runs to see if I can verify the in-game drop.

**Comment by DiomedesofHelos** [comment]
Thank you, that would be very generous of you! Do you want me to report it
as well, if I come across items in the game whos stat reqs aren't shown? A
little tip: A few of the items are shown as when held over by the mouse
cursor, when you simply google "titan quest *the name of the item*", and
then go to images. Although on rarer occasions, there's a link on the
normal search that takes you to a debate where someone has posted a picture
of the item where you can see the stats required. It could save you a
little time.

**Comment by fonsleenaars** [comment]
Yeah, for now just add them in this ticket somewhere (you can edit your original issue if you want, up to you).

That's true, but I never trust anything except the in-game screenshots anymore, and since Ragnarok a lot of those are outdated. But you're right, sometimes it's a nice way to verify!

**Comment by DiomedesofHelos** [comment]
Well I will send you screenshots then, each time I find any that doesn't
show stat req, and I do have ragnarok :) Creds to you doe not trusting
everything, I didn't think you would either. It's good to be sure that you
have the right information!

**Comment by fonsleenaars** [comment]
[Deathweaver's helmet](https://puu.sh/Bit1G/4f71d65a10.jpg) in Epic.

Level 25
Strength 368

I think the level requirement comes from the **Rugged** prefix, so now all I have to do is figure out where 368 Strength comes from!

**Comment by DiomedesofHelos** [comment]
Hmm interesting.

**Comment by fonsleenaars** [comment]
I've found one explanation, but there's absolutely no reference to this file from the Deathweaver's helmet file, but in what seems like a generic "requirement" calculation folder, a file called

`itemcost.dbr` has the following equation: `headStrengthEquation,50+((itemLevel-1)*7.75),`

The item level for Deathweaver's Helmet is 42, so plugging that in yields:

`50 + (41 * 7.75) = 367.5`

Now I just need to figure out how on earth it's determined that this calculation should be used!

**Comment by DiomedesofHelos** [comment]
Hmm good clue. Exciting..!

**Comment by fonsleenaars** [comment]
So what I've done is I've set this `itemcost.dbr` file as a fallback for any item that doesn't have a requirement.

I did limit it to **equipment**, not just all things in the database. I **think** it works now, but I only have the Deathweaver's Helmet as definitive proof. I've deployed it to staging so you can check it.

**Comment by DiomedesofHelos** [comment]
Awesome!! Thank you, hope it works for all the items then.:)

**Comment by DiomedesofHelos** [comment]
It's beginning to look really amazing. Thank you my friend :-)

**Comment by fonsleenaars** [comment]
No problem, I'll close this issue again, I think the issues you found have been address in the staging environment now right?

The 'of the Mammoth' will remain open for a while until I exclude it manually 😉

**Comment by DiomedesofHelos** [comment]
Yes, they have. :D

**Comment by DiomedesofHelos** [comment]
Hello! I just found an item "of the Mammoth"... This means that it is not
unused??? What's that supposed to mean?

Den lør. 25. aug. 2018 kl. 21.29 skrev Fons Leenaars <
notifications@github.com>:

**Comment by fonsleenaars** [comment]
Oh that's great, send me a screen shot!

**Comment by DiomedesofHelos** [comment]
By the way, do you know if a high level item for an example a MI on
Legendary can have ANY affix that fits to that sort of item? Like can a
high level item like Bandari's Greaves from legendary even have a low level
affix like "of Brawn" or "of Ability"?

**Comment by DiomedesofHelos** [comment]
Or is it limited to affixes above a certain amount of level requirement?

**Comment by fonsleenaars** [comment]
Good question, I'll look into it.

I think maybe the screenshot didn't upload? I don't see any yet ;)

**Comment by DiomedesofHelos** [comment]
And thank you =) I would love to know, because sometimes I want a bonus
where the highest level of that bonus maybe only requires you to be at
level 19, so I'm wondering if that affix can even drop on the high level
items I am planning to use :-)

**Comment by DiomedesofHelos** [comment]
If you still can't see the image, I found a helm which was "of the mammoth"
somewhere in Epirus on epic difficulty

**Comment by fonsleenaars** [comment]
Thanks, I'll take a look when I've got a moment and update my findings with the parser!

**Comment by DiomedesofHelos** [comment]
I found two more "odd" regular green items.
One is "of the Gryphon", which like "of the Mammoth" the site says that it
is not acquirable
Another item I found is a piece of leg armor with the "of Heroes" suffix,
which the site says can only be seen on chest armor?

Den tor. 30. aug. 2018 kl. 22.47 skrev Fons Leenaars <
notifications@github.com>:

**Comment by fonsleenaars** [comment]
Let's make a new issue with these affix bugs you've found ;)

**Comment by DiomedesofHelos** [comment]
Alright, sorry :)

**Comment by DiomedesofHelos** [comment]
Hey,

I just signed the petition "CD Projekt: Petition to add a "You're
Breathtaking" achievement on 100% completion of Cyberpunk 2077." and wanted
to see if you could help by adding your name.

Our goal is to reach 25,000 signatures and we need more support. You can
read more and sign the petition here:

http://chng.it/q5CvwHgdzh

Thanks!
Asger
