### ISSUE TITLE
Please increase http cache expiry time

### ISSUE THREAD

**Issue by KoderKrazy** [fonsleenaars/tqdb#40]
After every 24hr, the big png and bundle.js takes too much time to load on wifi and metered connections on mobile. Both of them combined are >7mb.

I think the cache expires every 24hr in chrome. I tried plugins to increase the cache time but it doesn't work.
If you could increase the expiry time by one week or a month it would be great.

e.g add something like this:
30 DAYS
location ~* \.(png|gif|js|css|swf)$ {
	add_header Cache-Control "max-age=2592000, public"
}

**Comment by fonsleenaars** [comment]
I'll update the configuration with the next deployment to increase the expiry time, thanks for the suggestion!

**Comment by fonsleenaars** [comment]
This has been implemented on both production and staging.
