### ISSUE TITLE
Affix bugs

### ISSUE THREAD

**Issue by DiomedesofHelos** [fonsleenaars/tqdb#44]
As of now I have found three "impossible" regular green items:
- An "of Heroes" leg armor, even though "of Heroes" is only supposed to be found on chest armor.
- An "of the Mammoth" helm, even though "of the Mammoth" isn't even supposed to be found at all. 
- An "of the Gryphon" arm armor, even though "of the Gryphon" is also not supposed to appear at all.

I've tried to send screenshots on e-mail, look for them there.

**Comment by fonsleenaars** [comment]
Thanks for reporting this in a separate issue. I don't think I've seen any e-mail with screenshots, I believe you should be able to drag and drop the screenshots in a comment, to attach them to this issue.

About the issues:
This is good news, I can use these to figure out what's going wrong with the Affix list, thanks!

**Comment by DiomedesofHelos** [comment]
Alright, hen I get home Ill try to send you the pictures as you described.
I would love to know if of the mammoth is possible on MI armor and jewelry,
because it's way better than of immortality which I'm planning on using so
far :D

**Comment by DiomedesofHelos** [comment]
![tqg](https://user-images.githubusercontent.com/39497756/44959466-bfe97e00-aeee-11e8-9b5f-5746f5332e74.PNG)
![tqh](https://user-images.githubusercontent.com/39497756/44959467-c546c880-aeee-11e8-81e7-a418a97f2975.PNG)
![tqm](https://user-images.githubusercontent.com/39497756/44959496-66ce1a00-aeef-11e8-999c-ebc5a0455a93.PNG)

**Comment by DiomedesofHelos** [comment]
I just noticed something else odd. An arms armor like "Druid WRISTLET of the Gryphon" isn't supposed to even be able to have a suffix is it? Can't it only have prefixes?

**Comment by DiomedesofHelos** [comment]
Remember that the game developers are still updating the game every now and then

**Comment by fonsleenaars** [comment]
I'll need to look into that too. I'll see if I can use the Druid Wristlet as an example. It's strange because I can't even find the file for that item, but I'm sure I just need to dig a bit more.

The approach for affixes is rather tricky, most files that can have affixes have properties likes: `suffixOnly`, `prefixOnly` or `prefixAndSuffix` and there's chances for all of those. But instead of having to parse every single possibility and then creating an index based on what affixes apply to those items, I simply parsed the affix loot tables per item type and assigned those as possible.

Either way, it's clear I'll need to look into affixes a lot more!

**Comment by DiomedesofHelos** [comment]
I'm very much looking forward to see the answer your research will find

**Comment by fonsleenaars** [comment]
Alrighty, I have found your Stygian Helm of the Mammoth example, and I think this will allow me to fix the parser.

It's going to take some changes, but this should definitely help make it more accurate. I'll update this issue once I've created a fix!

**Comment by DiomedesofHelos** [comment]
Okay looking forward to see, :)

**Comment by fonsleenaars** [comment]
I've pushed the fix, I'm just checking a few final things before it's pushed to production on the website.

**Comment by fonsleenaars** [comment]
Argh, have to re-open it. Almost everything is covered now, except your Dvergr Greaves revealed something.

These following two entries are from the Dvergr **Greaves**:

```
suffixRandomizerName1,records\xpack\item\lootmagicalaffixes\suffix\tablesarmor\torsomelee_e04.dbr
prefixRandomizerName1,records\xpack\item\lootmagicalaffixes\prefix\tablesarmor\torsomelee_e04.dbr,
```

These two lines indicate what kind of pre- and suffix can appear on the item. As you can see, they are referencing a **Torso** affix.

Sigh! I'll have to figure out what I'm going to do about that. If it's consistent (for example ALL greaves can have this) I'll add it, but if it's inconsistent, I'll probably end up making a separate list of special mentions.
