### ISSUE TITLE
Scripts on monsters page hangs

### ISSUE THREAD

**Issue by Gummiel** [fonsleenaars/tqdb#45]
When going to the monsters tab some scripts hangs and I have to terminate the script (making it thus impossible to swap to loot table or the different difficulties of each monster)

Using waterfox 56.2.2 (64-bit)
Windows 10 pro 64-bit

**Comment by fonsleenaars** [comment]
Thanks, I'll look into it. The monster page is by far the largest data set to load & render so I'll probably need to setup some sort of async/lazy load for it to not be a huge burden like that.

I'll try to get a fix out ASAP.

**Comment by fonsleenaars** [comment]
The [https://github.com/bvaughn/react-virtualized](https://github.com/bvaughn/react-virtualized) library will be used to speed up loading for all pages considerably.

I'll have it online tomorrow or the day after.

**Comment by fonsleenaars** [comment]
@Gummiel I have deployed a work-in-progress version to the staging environment. Could you try loading this website and letting me know if that works better for you? [https://staging.tq-db.net/monsters](https://staging.tq-db.net/monsters). Thanks!

**Comment by Gummiel** [comment]
works wonderfull, pretty much instant loading on that version

**Comment by fonsleenaars** [comment]
Ah, excellent. I want to include a few more fixes before I push everything to the main website but it will be up on tq-db.net within a day or two as well.

Thanks for the issue report, I'll close this once I've pushed it to production.
