### ISSUE TITLE
Site error/crash at small window widths

### ISSUE THREAD

**Issue by HumaneIsTaken** [fonsleenaars/tqdb#47]
I was checking out the responsiveness of your site when I noticed that when on the "Monsters" section of the website, resizing the window (to at least 880px) causes the site to spit out an error and require a refresh.

This same error occurs for other sections of the site (like Weapons/Armor) but at even smaller widths.

In any case, thanks for the site its a great resource!

**Comment by fonsleenaars** [comment]
Thanks for the report, I'll take a look. 

I'm in the middle of packing up for a big move so there might be a bit of a delay before I can push the next update. I'll try to find some time here and there. After October 3rd I'll be settling into my new place so time should free up a bit more.

**Comment by fonsleenaars** [comment]
I've deployed a fix that at least prevents the breaking. I'll still need to fix the styling so it doesn't look a bit messed up, I'll try to get that out this weekend too.

**Comment by fonsleenaars** [comment]
Crash was fixed, styling is being updated with the translation update coming up.
