### ISSUE TITLE
a mistake of Suffix

### ISSUE THREAD

**Issue by mikejames3151** [fonsleenaars/tqdb#53]
of Guile
equipment also can be in **arms(worrior)**
please add **arms(worrior)** in equipment

**Comment by fonsleenaars** [comment]
Thanks for rporeting it, I'll see what's going wrong with it and push an update once fixed.

**Comment by fonsleenaars** [comment]
Oops, it turns out it was already fixed on https://staging.tq-db.net/affix/suffixes but I just hadn't pushde the update to the main website yet. I'll push an update soon and close this when I do.

**Comment by fonsleenaars** [comment]
Added to the live website https://www.tq-db.net/affix/suffixes
