### ISSUE TITLE
I can't load your site

### ISSUE THREAD

**Issue by Talthybius** [fonsleenaars/tqdb#56]
Hi! I've been using your database for a really long period of time, so now, when I have a chance to thank you for this, I would like to it first of all. I think it's a greate idea to sum up every bit of information about this game, thanks for that:) However last 2 mounthes I coudn't load this site, I' ve tried different methodoes(a phone and a pc), but result was the same - google said(for this moment I was using google translator, 'cause my eng is too bad :( ): "The website www.tq-db.net can not establish a connection" just like it is on the screen below. Can you please give me some advise, because, considering the fact, that's there is no such theame here, I deceided the I am doing something wrong. If such theame exists pls sorry me for my inattention
![err](https://user-images.githubusercontent.com/47424566/52422950-2ad75a80-2b08-11e9-8c6d-a8a46758f507.png)

**Comment by fonsleenaars** [comment]
Hey! Glad to hear you enjoy the website.

Hm, that's definitely weird, could you try incognito mode? If that doesn't work could you try opening command prompt (Start => type "cmd" and start "Command Prompt").

In Command Prompt, type: `ping tq-db.net` and you should see something like:

```
Reply from 188.166.88.172: bytes=32 time=105ms TTL=53
Reply from 188.166.88.172: bytes=32 time=105ms TTL=53
Reply from 188.166.88.172: bytes=32 time=105ms TTL=53
Reply from 188.166.88.172: bytes=32 time=105ms TTL=53

Ping statistics for 188.166.88.172:
    Packets: Sent = 4, Received = 4, Lost = 0 (0% loss),
Approximate round trip times in milli-seconds:
    Minimum = 105ms, Maximum = 105ms, Average = 105ms
```

Then also in Command Prompt type `nslookup tq-db.net`, and you should see something like:

```
Server:  UnKnown
Address:  2605:a601:a204:10c9::1

Non-authoritative answer:
Name:    tq-db.net
Address:  188.166.88.172
```

**Comment by Talthybius** [comment]
I've just tryed opening site in incognito mode and got zero results, and then got the results in cmd the same as yours. Site was answering while I was pinging(tine = 43ms, ttl = 54). nslookup retutned results like yours (Adress(the first one) was different, but I think it's my own adress)

**Comment by fonsleenaars** [comment]
Alrighty, do you have any other browsers available? Firefox maybe?

Did you check the website on your mobile phone on mobile internet or on wi-fi? If you haven't checked it on mobile internet, try that.

Could you also have a friend check from their house, it might be a router/wifi issue/DNS issue locally. Do you use Google DNS? (If you don't know what this is I can explain that of course)

**Comment by Talthybius** [comment]
I've tried mozzila and got the same error, on my phone I was loading site with 4g connection, and my friend also tried using phone and than computer and also got error.
I don't know what is Google DNS, sorry

**Comment by Talthybius** [comment]
Hmm, I've installed VPN on my phone and opened the site "from GB" without any problems. If you would know, I live in Russia

**Comment by fonsleenaars** [comment]
Interesting! 

Could you try using this on your computer: https://developers.google.com/speed/public-dns/docs/using

That explains how to setup Google DNS, which means every website you load uses Google's lookup to determine where to send it.

If that doesn't work, I am not sure why the website is blocked in Russia, but I will look into it!

**Comment by Talthybius** [comment]
Ok, thanks for helping) I will write back here if I manage with Google DNS
