### ISSUE TITLE
Can't run run.py and prepare.py can't find game directory

### ISSUE THREAD

**Issue by chefranov** [fonsleenaars/tqdb#57]
Hi. I installed python on windows. I tryed to run your script `prepare.py` but your script can't find game directory
![screenshot_2](https://user-images.githubusercontent.com/2775475/53524583-76b66780-3ae8-11e9-8f48-a15e0e56ec62.png)
But i have the entry in registry
![screenshot_3](https://user-images.githubusercontent.com/2775475/53524693-c9901f00-3ae8-11e9-99a0-d45de90b0990.png)

After that I tried run manually your script. I ran `run.py` but also errors
![screenshot_4](https://user-images.githubusercontent.com/2775475/53524853-2e4b7980-3ae9-11e9-8944-e44aa9980dfd.png)

Can you help me?

**Comment by fonsleenaars** [comment]
Oops! You still have to execute this step from the manual setup:

Python
Python 3.6 or higher and Pipenv are required to run this project. To get started with a clean setup, open up a shell, navigate to your local repository, and run:

`pipenv clean`
`pipenv install`

I will update the documentation to include this mandatory setup step!

**Comment by chefranov** [comment]
When I run `pipenv clean`
![screenshot_5](https://user-images.githubusercontent.com/2775475/53525567-c26a1080-3aea-11e9-8887-98aece3ddb11.png)

**Comment by fonsleenaars** [comment]
Powershell seems to not recognize Python as being installed.

Can you try just typing `python` in your Powershell and see if it recognizes that command?

**Comment by chefranov** [comment]
![screenshot_6](https://user-images.githubusercontent.com/2775475/53525703-0d842380-3aeb-11e9-990b-00aa3d528674.png)

**Comment by fonsleenaars** [comment]
A yeah, so exit out of that by typing `exit()` and then type `pip install --user pipenv`

**Comment by chefranov** [comment]
![screenshot_7](https://user-images.githubusercontent.com/2775475/53525928-94390080-3aeb-11e9-917e-d4af44ed962e.png)
Next actions?

**Comment by fonsleenaars** [comment]
`pipenv clean`
`pipenv install`

Then autoinstaller again

**Comment by chefranov** [comment]
![screenshot_8](https://user-images.githubusercontent.com/2775475/53526426-d7e03a00-3aec-11e9-8480-e0a26923e090.png)

The same errors :(

**Comment by fonsleenaars** [comment]
I can help you later, still at work atm, sorry! I'll look at it tonight my time.

**Comment by fonsleenaars** [comment]
You might have to try running a regular command prompt, instead of powershell, and see if `pipenv clean` will run there. I think Powershell isn't loading `pip` loaded packages or something, I'm not sure.

**Comment by chefranov** [comment]
The same problem: pipenv is not command

**Comment by fonsleenaars** [comment]
Ok, in that command prompt: `pip install pipenv`, then `pipenv clean` and `pipenv install` again. We'll get there!

**Comment by chefranov** [comment]
![screenshot_1](https://user-images.githubusercontent.com/2775475/53569348-ad35c600-3b6c-11e9-90da-34477564ad2c.png)
Maybe Do I need to add something to PATH?

**Comment by fonsleenaars** [comment]
That should have happened when you setup Python, but I think they're not on the PATH at the moment. So yes, although you might want to google for "installing pipenv on Windows" and "PATH" in that query somewhere ;-)

I'm at work again (I live in the US now) so I'll be slower to respond.

**Comment by chefranov** [comment]
I fixed error, but now I have new issue :)
![screenshot_2](https://user-images.githubusercontent.com/2775475/53570887-3a2e4e80-3b70-11e9-8db5-ed5394845ab5.png)

**Comment by fonsleenaars** [comment]
Haha, wow I wasn't aware that 3.7 would check-fail 3.6, that's odd. I think you can just try running `pipenv install` and then running the autosetup again.

**Comment by chefranov** [comment]
A lot of errors
![screenshot_3](https://user-images.githubusercontent.com/2775475/53571252-191a2d80-3b71-11e9-9632-2ea9c9dda20d.png)

**Comment by fonsleenaars** [comment]
Try installing the packages in the `Pipfile` manually:

`pipenv install numexpr Pillow pytest`

**Comment by chefranov** [comment]
The same errors

**Comment by fonsleenaars** [comment]
Hm, what about `pip install numexp Pillow pytest` ?

**Comment by chefranov** [comment]
![screenshot_4](https://user-images.githubusercontent.com/2775475/53571529-d573f380-3b71-11e9-9718-6e1751c49c26.png)

**Comment by fonsleenaars** [comment]
Was that `pip` or `pipenv` install, that last screenshot? I don't see the `pip` but maybe I'm blind.

**Comment by chefranov** [comment]
ohh, it was my mistake
![screenshot_5](https://user-images.githubusercontent.com/2775475/53571974-deb19000-3b72-11e9-979b-e60ea85415b2.png)

**Comment by fonsleenaars** [comment]
Ah cool, so that works. Try the auto set pagain now , `python prepare.py`

**Comment by chefranov** [comment]
about `prepare.py` i wrote in first message. Script can't find game directory but directory exist

**Comment by fonsleenaars** [comment]
Open up `prepare.py` in your editor and edit these lines:

```python
def tqdb_prepare():
    # Open the TQAE key and grab the install location:
    try:
        tqae_key = winreg.OpenKey(
            winreg.HKEY_LOCAL_MACHINE, LOOKUP_KEY, 0, winreg.KEY_READ)
        install = winreg.QueryValueEx(tqae_key, 'InstallLocation')[0]
    except WindowsError:
        print('Could not find installation directory for Titan Quest')
        return
```

Add the exception the the `except` clause and print by changing that line to:

```python
    except WindowsError as we:
        print('Could not find installation directory for Titan Quest')
        print(we)

        return
```

**Comment by chefranov** [comment]
Here is https://stackoverflow.com/questions/46041719/windows-reports-error-when-trying-to-install-package-using-pipenv how to fix issue with pipenv on Windows

**Comment by chefranov** [comment]
```
C:\tqdb>python prepare.py
Could not find installation directory for Titan Quest
[WinError 2] can't find file
```

**Comment by fonsleenaars** [comment]
Ah! I think this might have something to do with 32 vs 64-bit systems.

Can you update this line in `prepare.py`:

```python
tqae_key = winreg.OpenKey(
            winreg.HKEY_LOCAL_MACHINE, LOOKUP_KEY, 0, winreg.KEY_READ)
        install = winreg.QueryValueEx(tqae_key, 'InstallLocation')[0]
```

To be:
```python
tqae_key = winreg.OpenKey(
            winreg.HKEY_LOCAL_MACHINE, LOOKUP_KEY, 0, access=winreg.KEY_READ | winreg.KEY_WOW64_64KEY)
        install = winreg.QueryValueEx(tqae_key, 'InstallLocation')[0]
```

Then try again. If that doesn't work, change `KEY_WOW64_64KEY` to `KEY_WOW64_32KEY` in that update, then try one more time!

**Comment by chefranov** [comment]
In first case
![screenshot_6](https://user-images.githubusercontent.com/2775475/53573129-731cf200-3b75-11e9-8136-6abb9dca8ac8.png)
In second case
![screenshot_7](https://user-images.githubusercontent.com/2775475/53573157-8039e100-3b75-11e9-95af-87b6fcc0aab0.png)

**Comment by fonsleenaars** [comment]
Ok, I'll have to debug this further, there's something going on with accessing the registry, I don't know if that has to do with a 32 vs 64-bit install of Python or something else, but I'll have to see what's causing this unable to lookup file.

You can still try to run through the Manual setup, that does the same as the Automated setup, just takes more effort.

**Comment by chefranov** [comment]
Okay, thanks. In the evening I check Manual setup.
And one more question. I read readme and there is mention that images of stuff is a sprite. How can I get separate images?

**Comment by fonsleenaars** [comment]
The parser creates a directory with all the images it then turns into a sprite, that it deletes at the end. I'll either add an option to not delete it, or show you where to turn off that delete from happening later.

**Comment by chefranov** [comment]
Yes, it will be cool

**Comment by chefranov** [comment]
I tried run manually but errors
How correct run manually?
![screenshot_1](https://user-images.githubusercontent.com/2775475/53586803-99508b00-3b91-11e9-916d-41e9704d7799.png)
Game is here E:\Games\SteamLibrary\steamapps\common\Titan Quest Anniversary Edition

**Comment by chefranov** [comment]
And `prepare.py` work! Previos time it was my mistake. Work with it: `winreg.HKEY_LOCAL_MACHINE, LOOKUP_KEY, 0, access=winreg.KEY_READ | winreg.KEY_WOW64_64KEY)`
What Do i need to do after `prepare.py`?

**Comment by chefranov** [comment]
Could you help me?

**Comment by chefranov** [comment]
Heeey?

**Comment by fonsleenaars** [comment]
Sorry! Work got really busy.

I remember running into some of those issues, but not these specific ones. I'll look into my logs later this week, sorry for the delay, busy busy! If we can't find a solution, maybe the quickest solution is to do some pair programming with Discord or something!

**Comment by chefranov** [comment]
Ok, thank you. I will waiting for you. Don't forget

**Comment by fonsleenaars** [comment]
Alright I've figured out a few things, it's a strange bug so I'm diving into it more this weekend, should have an update for you maybe Sunday.

**Comment by fonsleenaars** [comment]
Was traveling last 2 weeks, back home now.

Didn't get a solution that weekend I posted an update, trying again today & tomorrow!

**Comment by chefranov** [comment]
Okay
