### ISSUE TITLE
Add equipment types to affixes

### ISSUE THREAD

**Issue by fonsleenaars** [fonsleenaars/tqdb#6]
It's very useful for the affixes (pre- and suffixes) to list what equipment they apply to.

For the parser this means adding the equipment types (using the category names) to each affix.

For the website this means displaying this information, and allowing some basic filtering on the equipment types.

**Comment by LordVampir1983** [comment]
Similarly, if possible, I would like to know the chances of the appearance of certain affixes

**Comment by fonsleenaars** [comment]
That's possible, they're indexed just like loot tables so getting the chances should be possible
