### ISSUE TITLE
New suffix "of the Tinkerer" missing

### ISSUE THREAD

**Issue by DarthSomebody** [fonsleenaars/tqdb#60]
Hey, I found spears and head gear in the Atlantis DLC with the suffix "of the Tinkerer", which makes it possible to use 2 relics on that item. This suffix is not listed on TQDB.

**Comment by fonsleenaars** [comment]
Yep, I didn't realize its functionality at the time, will need to figure out how to get that description in there, might need to be a manual override.

Will try to get this in the 1.4.3 release.

**Comment by fonsleenaars** [comment]
This is deployed on staging and will go live with the 1.4.3 release.
