### ISSUE TITLE
Atlantean Artifice - Charm doesn't have the description

### ISSUE THREAD

**Issue by Sir-Mac** [fonsleenaars/tqdb#61]
Hi, 

there are few new relics and charms added with the "Atlantis" expansion. But one of them, the charm called "Atlantean Artifice" (and the epic and legendary counterparts) doesn't have the description. In the place of description, there is text "x3tag_animalpart04_desc". I believe, this is error made by creating the game files by the creators.

I ask you, if you can fix it, because the Atlantis expansion is now version 2.5 and I hope, it was fixed by the newest patch. If not, could you, report the bug to the creators as well, please
![Atlantean artifice](https://user-images.githubusercontent.com/50591247/57953952-cc353000-78f1-11e9-8180-5c50f586cf45.png)
?

I attach the screenshot, as always.

Sir-Mac

**Comment by fonsleenaars** [comment]
Thanks for reporting, I'll look into it this weekend and try to get another patch out

**Comment by fonsleenaars** [comment]
Yep, it seems to be missing in the locale files. I'll report the bug.

You can report bugs straight to THQNordic here by the way: https://redmine.thqnordic.com/projects/titan-quest-atlantis-community/news

**Comment by Sir-Mac** [comment]
Thank you, Fons Leenaars,

for letting me know about how to report the bugs to the game creators.

Just quick question - are you going to release patch to your TQ-DB.net, which will fix both of the issues, that I have mentioned? 

Thank you.

**Comment by fonsleenaars** [comment]
I'll try to release a new patch this weekend with a few fixes, the layout/menu/artifacts one for you will be high in the priority list.

**Comment by Sir-Mac** [comment]
Thank you, 

Fons Leenaars, for fixing the issue #59. (By the way, my resolution is 1600 x 900 px - it is today considered as LOWER resolution? :-) )

Now I hope, the atlantean artifice will be fixed in the game files and here as well.

**Comment by fonsleenaars** [comment]
> By the way, my resolution is 1600 x 900 px - it is today considered as LOWER resolution? :-)
Haha, I've just gotten too used to high vertical resolutions, my bad

> There are no new formulas or artifacts in the Atlantis expansion, it seems. Little bit disappointing for me, I have to say.

They exist in the database, but without any content, so I think that's a bug. I've reported it to THQ (https://redmine.thqnordic.com/issues/27263)

**Comment by Sir-Mac** [comment]
I can imagine, that creating new content to the game, as Titan Quest is, is not an easy task, but the Atlantis expansion doesn't seem to me to be fully complete and alpha / beta tested properly. 

Like collecting the fruits from the tree too soon ...

**Comment by fonsleenaars** [comment]
I'm sure they'll flush it all out. I love that they added a public issue tracker to report bugs, very cool move by them.

**Comment by Sir-Mac** [comment]
Hi, Fons Leenaars, 

I have some update for you and I hope, it will fix the trouble with the atlantean artifice description. In the locale files (looked into Czech and English one), there is "broken" string... "**Tagx3_animalpart04desc=**The strange contraption you assembled under Meidias' guidance is buzzing with electrical energy, ready to strike out at unsuspecting foes. {^n}{^y}Can enchant torso armor or shields."

I fixed the beginning of the string to "**x3tag_animalpart04_desc=**". It is located at any locale file, I used "text_cz.arc" and "text_en.arc". In those files, there are many txt files, after using "archivetool.exe". And the particular file is "x3basegame-nonvoiced.txt". If you want to check it out by yourself, please, tell me, if the fix works for you as well as for me.

**Comment by fonsleenaars** [comment]
I did see that one when I was checking the files (one of the things this parser does is extract all the files using that `archivetool.exe` file you mentioned 😉 ).

I would have to put in a manual fix for the parser just for this very item, in order to get the description to work. I might do that but first I would prefer to know:

- How does the item look in-game? Is the text also missing there
- If they fix the incorrect string `Tagx3` => `x3tag` I would need to revert my fix again anyway

I'll see if they bring out a patch soon and otherwise I'll add a manual fix to the parser.

Nice detective work!

**Comment by Sir-Mac** [comment]
Hi Fons Leenaars again,

I would give the developpers, let's say, one month to fix it. Because right now, I am in the middle of the first wave of the corrections, which I make in the czech localization. There is a lot of mistakes, in the Greek, Egyptian and oriental names in the czech localization. Czech language has proper transliteration for Greek, Egyptian and oriental names, so if the game files are translated via latin or via english, it is wrong... For example (for english speaking people) - no Osiris, but Usirev, no Apophis, but Apop (or Apep), no Hercules, but Heracles ...

For the nordic names and places, I have to borrow the books from the library and I will correct it during the main holidays (july and august).

There are also (partial or full) mistakes in the items' names ... And I want to fix it as well... 

So any new version means, I have to check the difference in the original locale files, which I haven't modified (2.5 vs 2.5a) and if there are any changes, I have to incorporate them in my fixed locale files.

Thank you for your understanding...

Sir-Mac

**Comment by Sir-Mac** [comment]
Hi, Fons Leenaars,

let me tell you, that Atlantean Artifice description tag is properly included within the localization text files in the Titan Quest - Atlantis, version 2.6. This topic, therefore, could be closed by you as solved one.

P.S. - My works of correcting the czech translation are progressing, but the last check will be done during the main holidays, having the books with all over the world mythologies...
