### ISSUE TITLE
mark the prefixes and suffixes with correct DLC (IT, Ragnarok, Atlantis)

### ISSUE THREAD

**Issue by graceoflives** [fonsleenaars/tqdb#64]
Hi fonsleenaars, thank you for this immensely helpful site. I just wonder if the prefixes and suffixes can be detected and marked by the DLC in which they are introduced (for example, the prefix `Allfather's` can be marked as R since it was introduced in Ragnarok).

**Comment by fonsleenaars** [comment]
That's a great idea, I'll get on it this weekend.

**Comment by fonsleenaars** [comment]
Done & live on tq-db.net (might need to hit F5).

You should know the affixes in Atlantis aren't active yet so you won't see a lot of them. Also I still need to fix the parser a bit to expand on some of the affix properties. Like `Tinkerer` allows more than 1 relic, but that's not a property easily parsed.
