### ISSUE TITLE
Weapon "Rhodian Sling" and "Electrum Sling" are not present in database

### ISSUE THREAD

**Issue by Sir-Mac** [fonsleenaars/tqdb#72]
Hi, Fons Leenaars,

the throwing weapon "Rhodian sling" is missing in your database. I can't find it by using search box.
 https://titanquest.fandom.com/wiki/Rhodian_Sling.
The throwing weapon "Electrum sling" is missing as well. https://titanquest.fandom.com/wiki/Electrum_Sling.

Thank you for adding the weapon to the database.

**Comment by fonsleenaars** [comment]
Interesting, I had this issue before (#32) with some weapons, I'll have to see what went wrong again.
