### ISSUE TITLE
Equipment type of the affixes

### ISSUE THREAD

**Issue by hjlixjtu** [fonsleenaars/tqdb#75]
Your tqdb shows that the prefix Veteran’s only appears on chest. However,  it can appear on many kinds of weapons.

**Comment by fonsleenaars** [comment]
Good catch, I have to revisit prefixes unfortunately, the way it handles it now isn't giving full coverage. It's a decent amount of work to index so I'll save it for this summer when I can take some time off to work on it.

Thanks for reporting

**Comment by hjlixjtu** [comment]
Thank you for your quick reply!
TQ equipments now support background color feature. As I observed, the background color of the equipments in shops depends on the type of the affixes. Might you add the type of the affixes in follow-up work?

**Comment by fonsleenaars** [comment]
Sure, I'll see if that's easy enough to implement and if it doesn't look bad I'll add it.

**Comment by fonsleenaars** [comment]
Fixed and will be shipped in the next update
