### ISSUE TITLE
Authorization request

### ISSUE THREAD

**Issue by hjlixjtu** [fonsleenaars/tqdb#77]
Dear TQDB producer,
      I am a member of the group named TQ Tie Ba in China. I enjoy surfing your web very much while playing TQ game. And we produce a off-line version and package it as a chm file.  Now we intend to release it on TQ Tie Ba for free. Of course, we will emphasize your great contribution. We would be grateful if you grant our authorization request.
      Thank you again for your work!

**Comment by fonsleenaars** [comment]
That's awesome!

Go for it, this parser was released as open source so that the data is available for everyone 👍
