### ISSUE TITLE
How to connect json data with sprite image?

### ISSUE THREAD

**Issue by chefranov** [fonsleenaars/tqdb#78]
I found [json file](https://www.tq-db.net/3b758ce648afc4c53b860fcb8bb5f414.json) with properties of items on your site and I am going to use on my page.
I read file via vue and fetch
![Screenshot_1](https://user-images.githubusercontent.com/2775475/60992115-8c6c5100-a354-11e9-9a7f-c12ebd9eae69.jpg)
And now I want to show image of item, which addon and loot table but I don't know how it connect. Could you help me?
And one more moment, json is too big (about 15mb) is it real divide on files by type?
Is it possible to create json file with better structure (link to image, type of addon, loot table and etc inside item object)?

**Comment by fonsleenaars** [comment]
Nice, hope that works out!

As it stands, no, the JSON file is formatted in such a way that almost everything is done through the unique tags that the game files define. The website (tq-db.net) is a React wrapper around that data set that sorts out how the sprite and JSON data combine together, since I didn't really think that should be a part of the data.

However, data from this parser has more than just the JSON and sprite output, it also has a CSS sheet, that maps the unique tags to the respective position ON the spritesheet, so with those three things you should get what you're looking for.

**Comment by chefranov** [comment]
I have problem with images. I saw sprite on your site, but I don't know coordinates for each item. Can you help?
my interpretation https://titanquest.org.ua/files/db/

**Comment by fonsleenaars** [comment]
You're missing the CSS file. If you run the parser you will get a `sprite.png` and `sprite.css` file. 

![sprite](https://user-images.githubusercontent.com/4301261/61172707-55fe2400-a556-11e9-81f4-e36f2a2d32b7.png)

[sprite.css.txt](https://github.com/fonsleenaars/tqdb/files/3388865/sprite.css.txt)

I had to rename the CSS file to TXT because GitHub doesn't allow the upload.

The CSS file is all coordinates.

**Comment by chefranov** [comment]
Thank you! Can give a new version of json with data? Recently TQ was updated, I thinks items proprties were also updated.
And in your json I found some items with name is "placeholder". What is it?
![Screenshot_6](https://user-images.githubusercontent.com/2775475/61172750-e0b04480-a591-11e9-9097-66c50009bdbe.jpg)
And russian version of file has properties in english (name of monsters and skills)
![Screenshot_7](https://user-images.githubusercontent.com/2775475/61172766-050c2100-a592-11e9-94f0-e634e5848e10.jpg)

**Comment by fonsleenaars** [comment]
I can't right now, the last version I pushed to this parser was for Atlantis and some other updates and there's a lot of data in the game files that seems to not be ready yet, but was picked up.

I filtered them manually on the website until I have a fix.

I'll use this ticket to mark off when those issues have been fixed, or if you want to contribute you can always feel free to open up a PR for them

**Comment by chefranov** [comment]
Images works!!
![Screenshot_9](https://user-images.githubusercontent.com/2775475/61172922-69c87b00-a594-11e9-8609-532c5774dca0.jpg)

**Comment by fonsleenaars** [comment]
The tags on the items:

`xTag` = Immortal Throne
`x2Tag` = Ragnarok
`x3Tag` = Atlantis

**Comment by chefranov** [comment]
One more question, how work loot table of item in your json?

**Comment by chefranov** [comment]
How can I detect this information (chest or equipped)?
![Screenshot at Aug 02 11-14-32](https://user-images.githubusercontent.com/2775475/62355079-f40e5a00-b516-11e9-92e6-a5e05772b8d4.png)

**Comment by chefranov** [comment]
Could you share with me new sprite.css and sprite.png?

**Comment by chefranov** [comment]
@fonsleenaars any updates?

**Comment by fonsleenaars** [comment]
I got it running again over Christmas, I'll see if I can push it, alongside some new instructions to get it running yourself, that way you can get your own files. Going to get reaquainted with the code this morning because it feels like a year since I last touched it 😅

**Comment by chefranov** [comment]
@fonsleenaars will be cool if it will work on windows and we can run it ourselves

**Comment by fonsleenaars** [comment]
@chefranov I run it on Windows myself so that should be easy enough. I don't work in python daily anymore so I'll just need to brush up a bit.

**Comment by fonsleenaars** [comment]
Alrighty, I managed to get the latest build running. I'll push some new instructions tomorrow with some bumps in dependencies, you should be able to generate the output yourself after that.

**Comment by chefranov** [comment]
@fonsleenaars we will wait for updates

**Comment by chefranov** [comment]
and if is it possible could you describe your json structure?

**Comment by fonsleenaars** [comment]
> and if is it possible could you describe your json structure?

You'll have to figure out the JSON structure yourself, it's generated by the python code so you can browse through the parsers to see what the output is.

It mostly sticks to a mapping of properties in the DBR to similar/identical properties on the parsed content, just without all of the noise.
