### ISSUE TITLE
Update database

### ISSUE THREAD

**Issue by chefranov** [fonsleenaars/tqdb#79]
Yesterday was big patch 2.8, which include a lot of changes in drop and item properties. When do you update your site?

**Comment by fonsleenaars** [comment]
It'll update this weekend

**Comment by fonsleenaars** [comment]
Hm, apparently something has gone wrong with the `Text` resources, the `ArchiveTool` only extracts `commonequipment.txt` and then throws a `Segmentation Fault` :/ 

I'll need to look into this, and maybe switch to another version if the update broke it.

**Comment by chefranov** [comment]
Any updates? Long time you don't update database :(

**Comment by fonsleenaars** [comment]
Haven't had any time or energy unfortunately, can't promise when I will I'm afraid

**Comment by fonsleenaars** [comment]
Got a day off, going to try to make some progress on this today

**Comment by chefranov** [comment]
It will be cool! Waiting for any updates.

**Comment by fonsleenaars** [comment]
Alrighty, with some manual fixing of the arc extractor, I managed to parse all the locales.

Going to inspect them and see how many fixes I need to apply, and then push them once ready to tq-db.net

**Comment by chefranov** [comment]
Nice!

**Comment by fonsleenaars** [comment]
Pushed to production, I need to work a bit on the required processes to get this repository up and running now that the current version of `ArchiveTool` won't work, so I'll probably include one of the alternatives in the `utils` directory.
