### ISSUE TITLE
two "Shadow Veil" items

### ISSUE THREAD

**Issue by afjback** [fonsleenaars/tqdb#82]
https://www.tq-db.net/en/search/shadow+veil
There are helm and artifact, both named Shadow Veil.
both link to
https://www.tq-db.net/en/equipment/shadow-veil
which leads to artifact, so you cannot hotlink the helm anyhow.

**Comment by fonsleenaars** [comment]
Will fix this soon by either prepending the category an item is in to the link, or having a unique tag identifier or something in front, thanks for reporting.

**Comment by fonsleenaars** [comment]
This is being fixed in the next 1.4.2 release, will go live within the next few days.

**Comment by fonsleenaars** [comment]
Live on staging: [https://staging.tq-db.net/en/search/shadow+veil](https://staging.tq-db.net/en/search/shadow+veil)

These will now link to two different links.
