### ISSUE TITLE
Editor name

### ISSUE THREAD

**Issue by lfdmotta** [fonsleenaars/tqdb#90]
Hi,

Is there currently a way to find the name of the item in the TQ Editor? For the DLCs items, they all have editor names like u_e_set01 so one cannot find the item by the name as it appears in www.tq-db.net.

**Comment by fonsleenaars** [comment]
No idea if this is still useful for you, but those `u_e_set01` correspond to names through the Resources. The `.arc` files in the TQ installed directory have a bunch of `.txt` files that have the corresponding names for all those tags.

This parser has some utility in `prepare.py` to extract those `.arc` files through the `ArchiveTool` that's included in Titan Quest, and then finds those tags and gets the real name for them.

Hope that helps (2 years late 😅 )
