### ISSUE TITLE
Missing item and weird behaviour of the website

### ISSUE THREAD

**Issue by Sir-Mac** [fonsleenaars/tqdb#91]
Hi, FonsLeenaars,

thank you for your wonderful website, it helped me a lot (altough the last update was done over a year ago) ... 

But let me inform you about two weird things:
1) Missing item - his name is "Hermes' Fine Gloves" and you can find the string in the english locale within the file x2uniqueequipment.txt, under the string "x2tagUArmor099=Hermes' Fine Gloves" [This is shown in the first screenshot of my message]

2) Weird behaviour of your site - If I try to search for Hermes' Fine Gloves, I can't find them, but that is not the weird part. The weird part is that if I want to search using "fine", the page goes black (probably background image or colour) and I can't do any other action [This is shown in the second screenshot of my message].

Thank you in advance,
Sir-Mac
![Gloves trouble](https://user-images.githubusercontent.com/50591247/87808664-65dfd080-c85a-11ea-9f42-30a06f2c214f.png)
![Fine trouble](https://user-images.githubusercontent.com/50591247/87808678-6aa48480-c85a-11ea-88ac-8d70080a3386.png)

**Comment by fonsleenaars** [comment]
@Sir-Mac gotta love somebody respond to you 2 years later but I'm getting around to this now 😅

**Comment by fonsleenaars** [comment]
FIxed the search issue, will be live in the next release. Looking into the missing item.

**Comment by fonsleenaars** [comment]
As for the first item (Hermes' Fine Gloves) I can't find a reference in any database file, have you managed to find it in the game? It's very possible this is an item that was never added

**Comment by fonsleenaars** [comment]
Let me know about the Hermes' Fine Gloves if you're still interested, the other issue has been fixed!

**Comment by Sir-Mac** [comment]
Hi, @fonsleenaars , how are you doing?

I haven't dropped "Hermes' Fine Gloves" yet, and I can't tell you, if the item is available to be dropped, that is something, which I can't tell you from the locale files. 

I would like to inform you that my czech correction of the game has been implemented into the version 2.10.3, so when this version is published (not only as a public test), you will have to parse the czech localization of the game to your website again. 

The only DLC, which hasn't been re-translated by me, is Eternal Embers, I am currently working on it ...

**Comment by fonsleenaars** [comment]
Yep sounds good, I'll run the parser a bit more frequently for updates they push out.

The Hermes' Fine Gloves probably aren't in the game, I'm working on getting more accurate loot tables figured out so I can mark things that aren't in the game as such 😄
