### ISSUE TITLE
Nymph Vines (Atlantis DLC Set)

### ISSUE THREAD

**Issue by MaelStream** [fonsleenaars/tqdb#92]
This set is in the database, but it is not actually a set in the game. In fact it cannot be a set, as the two items are both weapons, of which one is a 2-hand weapon, that can therefore not ever be equipped together with the other weapon, even if a dual wield class is chosen!

**Comment by Sir-Mac** [comment]
And what about having the first bow in the first weapon slot and the second bow in the second weapon slot? There are two weapon slots...

**Comment by MaelStream** [comment]
1. they are not bows, they are staffs
2. didn't you read the fact, that one of them is a 2-HAND WEAPON! It is IMPOSSIBLE to wear a 2-hand weapon AND a 1-hand weapon, no matter what skills you have!

**Comment by Sir-Mac** [comment]
Do you know, that you have switchable weapon slots? Do you know that you can have one weapon and shield on first pair of the slots and let's say staff or bow on second pair of the slots?

**Comment by MaelStream** [comment]
I do know that. But that is irrelevant, as only the weapon set, that is currently active counts towards set bonuses. As such my original reasoning is valid. It is IMPOSSIBLE to have both weapons active at the same time to get a set bonus. Even if the items were a set, which they are simply not, as nothing in game points to that.

**Comment by Sir-Mac** [comment]
OK. But what can Fons Leenaars do about it? I think you are barking up a bad tree.

**Comment by MaelStream** [comment]
my question is, why this set is in the database at all, as there seems to be no indicator in the game, that these items are in a set at all...

**Comment by fonsleenaars** [comment]
@MaelStream 2 years late to the party, but maybe I can shed some light 😉 

The parser basically scans ALL the files and dumps them into the different categories (armor, sword, etc). For some of those items they were never added to the game and are just placeholder/unfinished stuff. This appears to be one of them.

At some point I'll try to make the parser _only_ display items that can drop based on loot tables, quest rewards, etc. For now I'm afraid you'll find some odd stuff in there, but if the loot table is empty that means I haven't found a way to tell you where you can get it from.
