### ISSUE TITLE
Acragas' Polished Greaves - Wrong visual

### ISSUE THREAD

**Issue by TheWagi** [fonsleenaars/tqdb#94]
Hey o/

The visual of those items seems inverted.
TQ DB Link: [https://www.tq-db.net/en/equipment/acragas'-polished-greaves](url) 
Statistics: OK
Name: OK
Visual: NOK, the correct visual is of this items: [https://www.tq-db.net/en/equipment/blue-actinia](url)
In-Game: [https://cdn.discordapp.com/attachments/672458358673899541/795058059394940978/20210102232306_1.jpg](url)

Wagi

THQ Nordic Moderation

**Comment by fonsleenaars** [comment]
Thanks for reporting. It's been a while since I've worked on this unfortunately. If I find myself with some spare time I'll add this to the pile 👍

**Comment by fonsleenaars** [comment]
@TheWagi I'm finally getting around to a few thins, your in-game link expired 😅 Would you mind pasting it again or verifying this is still busted?

**Comment by fonsleenaars** [comment]
For your convenience:

[https://www.tq-db.net/en/equipment/acragas'-polished-greaves](https://www.tq-db.net/en/equipment/acragas'-polished-greaves)

[https://www.tq-db.net/en/equipment/blue-actinia](https://www.tq-db.net/en/equipment/blue-actinia)

**Comment by TheWagi** [comment]
https://cdn.discordapp.com/attachments/672458358673899541/978833311805878292/unknown.png

**Comment by TheWagi** [comment]
Well, it's actually fine now

**Comment by fonsleenaars** [comment]
Awesome, thanks for checking for me, I'll close this out
