### ISSUE TITLE
Charm - Golem Heart - Statistics of a charm chard instead of completed charm.

### ISSUE THREAD

**Issue by TheWagi** [fonsleenaars/tqdb#95]
Hey o/

There is an issue with the statistics on the "Golem Heart" charms (Normal, Epic, Legendary).
The value of the % of chance is the one of a char of charm and not the completed charm like all other charm on the DB.

The % of chance should be 5x the actual one when completed so 50% instead of 10%.

TQDB: https://www.tq-db.net/en/search/golem+heart
In-Game:

- Normal: https://media.discordapp.net/attachments/672458358673899541/819200124189802507/20210310142401_1.jpg
- Epic: https://media.discordapp.net/attachments/672458358673899541/819200123019198494/20210310142359_1.jpg
- Legendary: https://media.discordapp.net/attachments/672458358673899541/819200125808541726/20210310142406_1.jpg

Wagi

THQ Nordic Moderation

**Comment by fonsleenaars** [comment]
👍 Thanks for the report!

**Comment by fonsleenaars** [comment]
Finally figured out what's going on here;

```
defensiveReflect,30.000000,
defensiveReflectChance,10.000000;20.000000;30.000000;40.000000;50.000000,
```

My parser incorrectly only sees 1 value for the `defensiveReflect` property and just grabs the first value for the Chance, instead of inversing the logic and saying "the value is static but the chance is dynamic"

Will be fixed in the upcoming release.
