### ISSUE TITLE
Ragnarök-version of Outrider's gear missing

### ISSUE THREAD

**Issue by artydent** [fonsleenaars/tqdb#97]
It seems that Ragnarök introduced a new version of *Outrider's Tunic* and *Outrider's Skullcap* (not the Buckler though) with better stats (and also a different look in case of the tunic), but the TQDatabase (v1.3.10) only lists the original version.

**Outrider's Tunic:**
original version:
RECORDS\ITEM\EQUIPMENTARMOR\MI_x_CENTAUR.DBR (x = N, E, L)
![OutriderTunic-Original](https://user-images.githubusercontent.com/81525952/112762604-cbe34100-9000-11eb-85b3-317fe8044e4a.png)

Ragnarök version:
RECORDS\XPACK2\ITEM\EQUIPMENTARMOR\TORSO\MI_x_CENTAUR.DBR (x = N, E, L)
![OutriderTunic-Ragnarok](https://user-images.githubusercontent.com/81525952/112762622-ec130000-9000-11eb-8864-f82d6bbff1aa.png)

**Outrider's Skullcap:**
original version:
RECORDS\ITEM\EQUIPMENTHELM\MI_x_CENTAUR.DBR (x = N, E, L)
![OutriderSkullcap-Original](https://user-images.githubusercontent.com/81525952/112762852-46609080-9002-11eb-861f-fb1c17495cb3.png)

Ragnarök version:
RECORDS\XPACK2\ITEM\EQUIPMENTARMOR\HELM\MI_x_CENTAUR.DBR (x = N, E, L)
![OutriderSkullcap-Ragnarok](https://user-images.githubusercontent.com/81525952/112762873-5aa48d80-9002-11eb-9091-031c027e56ce.png)

No idea if the new version replaces the old one (if Ragnarök is installed) or if both can drop in this case. I had only drops of the Ragnarok version so far.

PS: Thanks for making this awesome website!

**Comment by fonsleenaars** [comment]
These will be in the new release, but I believe the loot table for it isn't 100% correct yet. That will be fixed in another update
